### ISSUE TITLE
notes changes doesnt saved

### ISSUE THREAD

**Issue by lex93ushakov** [amejiarosario/todoAPIjs#2]

**Comment by amejiarosario** [comment]
@lex93ushakov did you try with this repo? or your own project following the [post](http://adrianmejia.com/blog/2014/10/01/creating-a-restful-api-tutorial-with-nodejs-and-mongodb/)?

**Comment by lex93ushakov** [comment]
This repo.

**Comment by amejiarosario** [comment]
It works...
![todoapijs](https://cloud.githubusercontent.com/assets/418605/21862072/ae365ba4-d805-11e6-9391-eba2aec9c253.gif)
